# Generated by Django 4.2.7 on 2025-08-05 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0008_news_boardnotification'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='property_occupied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landlord.apartment'),
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse'), ('child', 'Child'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('other', 'Other')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='dependent_photos/')),
                ('id_type', models.CharField(choices=[('national_id', 'National ID'), ('voters_card', "Voter's Card"), ('drivers_license', "Driver's License"), ('international_passport', 'International Passport'), ('other', 'Other')], max_length=30)),
                ('id_number', models.CharField(max_length=50)),
                ('medical_notes', models.TextField(blank=True, help_text='Allergies, disabilities, etc.', null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='tenant.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
