# Generated by Django 5.2.2 on 2025-06-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('landlord', 'Landlord'), ('tenant', 'Tenant')], help_text="Individual's position in the system (e.g., Landlord, Tenant).", max_length=20, null=True),
        ),
    ]
