# Generated by Django 4.2.7 on 2025-06-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0002_alter_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
    ]
