# Generated by Django 4.2.7 on 2025-07-10 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0006_dependent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('residential_address', models.TextField()),
                ('government_id', models.FileField(blank=True, null=True, upload_to='security_ids/')),
                ('position', models.CharField(choices=[('security_guard', 'Security Guard'), ('patrol_officer', 'Patrol Officer'), ('cctv_monitor', 'CCTV Monitor'), ('supervisor', 'Security Supervisor'), ('other', 'Other')], max_length=30)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('temporary', 'Temporary')], max_length=20)),
                ('joining_date', models.DateField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='security_photos/')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether the security personnel is approved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_personnel', to='landlord.landlord')),
            ],
            options={
                'verbose_name_plural': 'Security Personnel',
                'ordering': ['-created_at'],
            },
        ),
    ]
