# Generated by Django 4.2.7 on 2025-07-10 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0007_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('excerpt', models.CharField(help_text='Brief summary of the news', max_length=300)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('category', models.CharField(choices=[('general', 'General'), ('security', 'Security'), ('maintenance', 'Maintenance'), ('event', 'Event'), ('announcement', 'Announcement'), ('emergency', 'Emergency')], default='general', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_articles', to='landlord.landlord')),
            ],
            options={
                'verbose_name_plural': 'News Articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoardNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('complaint', 'Complaint'), ('security_alert', 'Security Alert'), ('help_request', 'Help Request'), ('suggestion', 'Suggestion'), ('maintenance_request', 'Maintenance Request'), ('general', 'General')], default='general', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=15)),
                ('is_read', models.BooleanField(default=False)),
                ('admin_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_notifications', to='landlord.landlord')),
            ],
            options={
                'verbose_name_plural': 'Board Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
